### ISSUE TITLE
tDOM link problem under windows...

### ISSUE THREAD

**Issue by petasis** [tDOM/tdom#11]
Hi,

I am facing a linking problem when trying to cross-compile tDOM for Windows under Fedora.
The error is:

[tcl@server tdom]$ make
rm -f libtdom0.8.3.so
i686-w64-mingw32-gcc -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -pipe -O2 -fomit-frame-pointer -Wall -Wno-implicit-int -fPIC  -Wl,--export-dynamic  -o libtdom0.8.3.so xmlrole.o xmltok.o xmlparse.o xmlsimple.o utf8conv.o dom.o domhtml.o domxpath.o domxslt.o domlock.o tcldom.o nodecmd.o tdominit.o tclexpat.o tdomStubInit.o  -L/home/tcl/binaries/win32-ix86/lib -ltclstub86 
/usr/lib64/gcc/i686-w64-mingw32/4.7.0/../../../../i686-w64-mingw32/bin/ld: warning: --export-dynamic is not supported for PE targets, did you mean --export-all-symbols?
dom.o: In function `TclTdomObjCmd':
/home/tcl/sources/tdom/./generic/dom.c:5189: undefined reference to`_imp__CheckExpatParserObj'
/home/tcl/sources/tdom/./generic/dom.c:5310: undefined reference to `_imp__CHandlerSetGetUserData'
/home/tcl/sources/tdom/./generic/dom.c:5275: undefined reference to`_imp__CHandlerSetGetUserData'
/home/tcl/sources/tdom/./generic/dom.c:5209: undefined reference to `_imp__CHandlerSetCreate'
/home/tcl/sources/tdom/./generic/dom.c:5225: undefined reference to`_imp__GetExpatInfo'
/home/tcl/sources/tdom/./generic/dom.c:5254: undefined reference to `_imp__CHandlerSetInstall'
/home/tcl/sources/tdom/./generic/dom.c:5324: undefined reference to`_imp__CHandlerSetRemove'
/home/tcl/sources/tdom/./generic/dom.c:5258: undefined reference to `_imp__CHandlerSetGetUserData'
/home/tcl/sources/tdom/./generic/dom.c:5263: undefined reference to`_imp__GetExpatInfo'
/home/tcl/sources/tdom/./generic/dom.c:5269: undefined reference to `_imp__tcldom_returnDocumentObj'
/home/tcl/sources/tdom/./generic/dom.c:5359: undefined reference to`_imp__CHandlerSetGet'
/home/tcl/sources/tdom/./generic/dom.c:5336: undefined reference to `_imp__CHandlerSetGetUserData'
collect2: error: ld returned 1 exit status
make: **\* [libtdom0.8.3.so] Error 1
[tcl@server tdom]$ 

I am using the configure/make build environment, not the windows makefile. There seems to be a difference between these two, I think that stubs are build under unix, but I am not sure they are built under windows.

Configure/make succeeds under Linux, it fails only while cross-compiling.

Can this be fixed?

**Comment by petasis** [comment]
Actually, I have found the cause of the problem - it is not the build system. 
tclexpat.h assumes that the compiler will always be the microsoft one, and fails to define
TCL_STORAGE_CLASS as DLLEXPORT under mingw.
Can you please apply the following patch?

diff --git a/generic/tclexpat.h b/generic/tclexpat.h
index 42ed06c..f59a135 100644
--- a/generic/tclexpat.h
+++ b/generic/tclexpat.h
@@ -144,7 +144,7 @@ typedef struct TclGenExpatInfo {
 |
 -------------------------------------------------------------------------*/

-#if defined(_MSC_VER) || defined(BUILD_tdom)
+#if defined(_MSC_VER) || defined(BUILD_tdom) || defined(__MINGW32__) || defined(**MINGW64**)
 #  undef TCL_STORAGE_CLASS
 #  define TCL_STORAGE_CLASS DLLEXPORT
 #endif

(That is check for the symbols 2-undersores MINGW32 or MINGW64 2-underscores - the patch is not shown correctly)

**Comment by petasis** [comment]
And there is also a second fix, for exporting the Tdom_init() functions from the dll:

--- a/generic/tcldom.h
+++ b/generic/tcldom.h
@@ -62,7 +62,7 @@ Tcl_ObjCmdProc TclExpatObjCmd;
 Tcl_ObjCmdProc tcldom_unknownCmd;
 Tcl_ObjCmdProc TclTdomObjCmd;

-#if defined(_MSC_VER)
+#if defined(_MSC_VER) || defined(__MINGW32__) || defined(**MINGW64**)
 #  undef TCL_STORAGE_CLASS
 #  define TCL_STORAGE_CLASS DLLEXPORT
 #endif

**Comment by petasis** [comment]
With these two changes, tdom compiles under Fedora 17, having as cross-compilation targets win 32/64.
Can these two simple fixes be added to the sources?

**Comment by pointsman** [comment]
Petasis, could you write here, what tools you use and what are the steps to cross-compile tdom on linux for windows with them? After I've verified your findings, I'll add the necessary modifications. Thanks.

**Comment by petasis** [comment]
I am not sure what you are asking here. I use mingw32/mingw64 to compile.
You want to install fedora, setup the crosscompiler, and build the sources to get the errors I already reported?
The patch is simple enough: what is done when _MSC_VER is defined, must be done when __MINGW32__ or **MINGW64** are defined.

**Comment by pointsman** [comment]
Yes, at the ground of it I want to reproduce the problem, study it and
then do what seems best to me to the tdom package.

What I was asking for, was a small description about how to
cross-compile tDOM on linux for windows - the pre-requisits, the
toolset you used (ideally in terms of links to downloads, not package
names of a certain distribution), the needed env settings, the
configure call (if something special) - such things.

I didn't use fedora at all and I didn't cross-compiled any software
within the last decade or so. But I did cross-compile software on
linux for windows around ten years ago and ISTR that I build tcl using
mingw on linux for windows and on windows.

I looked into this issue two weeks ago. From looking around on the web
it was not immediately clear to me, which of the mingw projects are
the right/best to pick. I gave one mingw64 version of them a try
(haven't access to the box, on which I did this, atm, I'm away on
vacation on crete, can't say exactly from memory which one I tried),
build the toolset but failed to compile tdom because of a seg fault of
the compiler during compilation. Lacking time, I didn't investigated
any deeper.

In the case you brought up it may seem OK, to just add, what you
request. From looking at it, it probably doesn't do harm and it
doesn't do add too much ifdef clutter. But in general I think it isn't
a great idea, to just apply any contributed patches without looking at
the case yourself. The bug reporter has his problem and is happy with
_a_ solution for this. This solution isn't always the best from
looking from a more general point of view.

From just looking around some questions raise there head. In tcl.h
there seems to be some build magic needed for both import and export
on windows. tDOM extensions, as the with the core shipped tnc, link
againts tdom lib. Is there something more needed than your patch to
make a cross-complied tnc load into a tclsh with cross-compiled tdom?
And, I see no mention at all of MINGW64 within the tcl sources. How do
you link your cross-compiled 64-bit tdom? And such things.

While working for a living, I often enough have to pick a solution,
that 'seems to work good enough'. Though I use tdom in business a lot,
maintaining it is mostly a spare time effort. And I this cases, I love
to understand, what I do to some deeper degree.

**Comment by pointsman** [comment]
I used x86_64-w64-mingw32-gcc (GCC) 4.8.1, build with the help of mingw-w64-build-3.5.0 (http://zeranoe.com/scripts/mingw_w64_build/mingw-w64-build-3.5.0) and it turns out, that there is no need to check for __MINGW64__, __MINGW32__ will be defined even if cross-compiling for win64. tnc needed a similar modification, but otherwise cross-compilied and worked. Works everything very pleasant, now, at least for me.
