### ISSUE TITLE
Please, stop bundling expat

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [tDOM/tdom#27]
It is perfectly acceptable to list expat as a dependency -- you do not need to bundle your own (inevitably outdated) version.

The only obstacle to removing it immediately is the shortcuts using constants in `expat/nametab.h` (included from `generic/dom.h`). That usage seems "unofficial" and will, likely, break in the future. I also suspect, it may _already_ be working incorrectly for some "exotic" locales (non UTF8).

**Comment by kolewu** [comment]
The github Repo is no longer active. AFAIK the development has completely moved to Fossil: http://core.tcl.tk/tdom

**Comment by pointsman** [comment]
UnitedMarsupials wrote:
> It is perfectly acceptable to list expat as a dependency -- you do
> not need to bundle your own (inevitably outdated) version.

The user is already able to link with every exapt library that pleases
him, via configure switch -with-exapt=... That's enough for me. And
it's enough for at least the distribution package maintainer, I'm in
contact with.

Or put in another way: You do not need to use the bundled expat. Enjoy
your freedom.

> The only obstacle to removing it immediately is the shortcuts using
> constants in `expat/nametab.h`. That usage seems "unofficial" and
> will, likely, break in the future. I also suspect, it may _already_
> be working incorrectly for some "exotic" locales (non UTF8).

Surely, the future is uncertain. Things may break.

Atm they work well, AFAIK.

If you have facts that indicate something else, please provide them
with adequate detail. Thanks.

Otherwise, please, stop spreading FUD.

**Comment by UnitedMarsupials-zz** [comment]
> via configure switch `-with-expat=...` [...] You do not need to use the bundled expat.

As long as tdom's code includes an _internal_ header (`<../expat/nametab.h>`), that is not sufficient -- because I still must have expat's sources at compile time.

> Atm they work well, AFAIK. [...] stop spreading FUD.

You are using _unpublished_ API from a 3rd-party library in a way, the library's authors do not approve. It is not "spreading FUD" to question such an approach.

> If you have facts that indicate something else, please provide them with adequate detail.

Well, I certainly can't parse any XML with `encoding` set to anything other than UTF-8 -- I get the "invalid encoding" error.

**Comment by UnitedMarsupials-zz** [comment]
FWIW, I just committed an upgrade to the [FreeBSD port of tdom](https://www.freshports.org/www/tdom/). The port now makes a point to not even extract the `expat/` bits _except_ the `nametab.h`, which, unfortunately, remains mandatory for the time being.

Even if one uses `--with-expat=/somewhere/else`, `generic/dom.h` still includes `"../expat/nametab.h"`, which I consider undesirable.

Whether or not tDOM avoids such usage of undocumented and unpublished bits of expat in the future, I urge you to stop bundling _other_ pieces of the library now -- just declare it as a dependency (like gumbo).

**Comment by pointsman** [comment]
I'm sure you're willing to do good, but please sit back, take a breath.

Ami 02/05/2018 08:11 PM, UnitedMarsupials wrote:
>> You do not need to use the bundled expat.
>
> As long as tdom's code includes an _internal_ header
> (`<../expat/nametab.h>`), that not sufficient -- because I still
> must have expat's sources at compile time.

Well, you have it, because it's bundled. I don't know, what you care
about?

Have you looked into nametab.h? This is only data. And it's used in
other parts of the software than parsing XML with the help of expat.

If you are keen about the expat version used for parsing, --with-expat
is your friend.

>> Atm they work well, AFAIK. [...] stop spreading FUD.
>
> You are using _unpublished_ API from a 3rd-party library in a way,
> the library's authors do not approve. It is not "spreading FUD" to
> question such an approach.

No, I just use data. It's that simple.

>> If you have facts that indicate something else, please provide them
> with adequate detail.
>
> Well, I certainly can't parse any XML with `encoding` set to
> anything other than UTF-8 -- I get the "invalid encoding" error.

This unfortunately doesn't provide many details. If you have problems
parsing well-formed XML files with tcl/tDOM this is most probably
pilot error. Are you aware of xmlReadFile / xmlOpenFile?

**Comment by UnitedMarsupials-zz** [comment]
> Well, you have it, because it's bundled. I don't know, what you care about?

I don't like such bundling not only because it wastes diskspace, RAM, and bandwidth, but because it raises gratuitous questions and concerns:

- There is a security advisory about expat -- is the version tDOM is using safe?
- Something does not work -- is that because we used a different expat from what tDOM uses (and tests against)?
- When we compile against a different expat-library, are we sure, the alternative headers aren't mixing up with the bundled ones, possibly creating a conflict between declarations and definitions?

You may dismiss it all as "FUD", but it would be better, in my not so humble opinion, to sidestep all of the above questions and just make expat (of a certain minimum version) a dependency (like jumbo).

> No, I just use data.

Then you may as well add the data to your own code (`generic/`) and get rid of the rest of `expat/`.

> This unfortunately doesn't provide many details.

Ok, here it is. This snippet works*
```tcl
package require tdom

set xml	[dom parse {<?xml version="1.0" encoding="UTF-8"?>
<ма>Me</ма>
}]
puts $xml
```
This does not:
```tcl
package require tdom

set xml	[dom parse {<?xml version="1.0" encoding="KOI8-U"?>
<ма>Me</ма>
}]
puts $xml
```
The only difference is the `encoding`-attribute.

*Now, when I say "works", I mean "parsing succeeds". I'm afraid, the name of the tag ("ма"), which is in Cyrillic, is misparsed as UTF8 -- but I do not know, how to verify it...  But you do...

**Comment by pointsman** [comment]
> I don't like such bundling not only because it wastes diskspace,
> RAM, and bandwidth,

Please, come on. Have you looked at the facts? File sizes and memory
usage were talking about here? Using tcl / tDOM saves you so much file
space and runtime memory compared with other tools, that this is
hardly anything even near a real problem.

Especially if there is more to consider then just the one single
(good) advice "don't waste resources".

To start with: tDOM works on platforms on which you can't expect a
system expat lib (most obvious Windows). For this users a bundled
expat is obviously convenient.

> but because it raises gratuitous questions and concerns:
>
> - There is a security advisory about expat -- is the version tDOM is  using safe?

You have to check this if you use the included expat version as well
as if you've build with something else, no?

Since its perfecly leagal (and used practice of some linux
distributions that include tDOM) to not build with the included expat,
tDOM helps you in getting this question answered. Read about the [dom
featureinfo ...] command.

> - Something does not work -- is that because we used a different  expat from what tDOM uses (and tests against)?

See, how convenient it is to have the "blessed" expat version bundled.
All you need to compare with is already at your hands.

> - When we compile against a different expat-library, are we sure,
> the alternative headers aren't mixing up with the bundled ones,
> possibly creating a conflict between declarations and definitions?

Yes.

Did you actually looked more than glancing over at the code? Are you
used to C? Could you describe more clearly, what makes you unsure?
Other than "possibly" anything may happen?

> You may dismiss it all as "FUD", but it would be better, in my not
> so humble opinion, to sidestep all of the above questions and just
> make expat (of a certain minimum version) a dependency (like jumbo).

I understand that you are eager to make you point. But you are
spreading FUD.

You don't like how things are because you rule some things in another
way than I do. There are costs and benefits, reasons even, to argue
about.

But there is no real problem with bundling expat. What real harm does
it to you other than you have to ignore it? Just the fact that expat
is bundled doesn't impose any additional problem. They are just
ordinary files, nothing magically toxic.

>> No, I just use data.
>
> Then you may as well add the data to your own code (`generic/`) and
> get rid of the (`expat/`).

In principle yes, of course. But it give clear credit, saves space,
since the data is already there in the bundled expat and it guarantees
a nice symmetry: the other parts of tDOM needed to create XML data
have exactly the same definition of character classes (nameStart,
nameChar etc.) as the parser (if build with the bundled (tested
against) exapt).

>> This unfortunately doesn't provide many details.
>
> Ok, here it is. The snippet works*
> ```tcl
> package require tdom
>
> set xml	[dom parse {<?xml version="1.0" encoding="UTF-8"?>
> <ма>Me</ма>
> }]
> puts $xml
> ```
> This does not:
> ```tcl
> package require tdom
>
> set xml	[dom parse {<?xml version="1.0" encoding="KOI8-U"?>
> <ма>Me</ма>
> }]
> puts $xml
> ```
> The only difference is the `encoding`-attribute.
>
> Now, when I say "works", I mean "parsing succeeds". I'm afraid, the
> name of the tag ("ма"), which is in Cyrillic, is misparsed as UTF8
> -- but I do not know, how to verify it... But you do...

This is just misuse of the software (pilot error). This looks like you
(sorry) miss some basic concepts.

This has nothing to do in any way I could see with the fact that expat
is bundled.

If you have raised the topic because you've such basic usage problems
please look at the Tclers wiki at http://wiki.tcl.tk/ and search for
examples or contact me per PM.

**Comment by UnitedMarsupials-zz** [comment]
> Have you looked at the facts? File sizes and memory usage were talking about here?
Yes, I have. Consider:
 - Including the private copy of expat in `libtdom0.9.0.so` increases the shared library's size 30% here on FreeBSD/amd64 -- from 457597 to 624068. That's 162Kb of not only diskspace, but also runtime RAM. Because, whereas the external libexpat is, in all likelihood, also in use by other processes, the private copy inside libtdom is usable only by Tcl
- Removing `expat/` from the distribution tarball reduces the size by 10% -- that's diskspace _and_ bandwidth for your server, every mirror, and every end-user choosing to build from source

> Using tcl / tDOM saves you so much file space and runtime memory compared with other tools

This would've been relevant, if the change I advocate somehow conflicted with these savings.

> See, how convenient it is to have the "blessed" expat version bundled.
If you find it acceptable to question my command of C, allow me to wonder, whether you understand English. The two examples I offered were meant to show the dilemma you force upon people by bundling expat with your code.

On the one hand, any expat-related CVE increases the worry -- one can update the installed expat taking care of all packages using the library, but the tDOM installation will require a _separate_ additional update.

Your own reference to the bundled expat as "blessed" breeds the FUD. Whenever one has a problem, one inevitably fears, doubts, and is uncertain over whether it is due to his own "pilot error" or because of some subtle incompatibility with the "blessed" version.

> There are costs and benefits, reasons even, to argue about.

There aren't. The case is perfectly clear cut -- bundling 3rd party libraries is bad. The advice [FreeBSD gives to porters](https://www.freebsd.org/doc/en/books/porters-handbook/bundled-libs.html) is applicable to any other OS and "distro".

Including Windows -- you don't need to bundle expat inside your own tarball to help people building on that hideous platform. You can just tell them, they have to download it on their own before building.

> Did you actually looked more than glancing over at the code?

I did. You `#include <expat.h>` in a number of places. _Currently_ the `Makefile` sets `-I` flags correctly, but some day you are bound to overlook something and the `-Iexpat` will get in there even if an external expat is requested. The declarations from the bundled `expat.h` may have a subtle disconnect from the definitions in the external `-lexpat`.

> Just the fact that expat is bundled doesn't impose any additional problem.

It does, I enumerated them. They aren't horrible, but they are problems nonetheless.

Lastly -- you don't bundle gumbo, do you? Well, stop bundling expat for the same reason, whatever they are.

I've said all I could -- for the record...

**Comment by pointsman** [comment]
Lemme repeat what I wrote in my first reply: You are perfectly free to
use your system expat. Debian does, SuSE does. No increased shared
library size, no unnecessary runtime memory.

No problem here. And if you really care about 10 percent of tar ball
size of an already small package, what about another resource: your
and my time?

I don't sympathize much with windows either. But I dislike, that you
tell me I should tell other people to do more work "on there own"
instead of being helpful.

English is in fact a foreign language to me. But I know the software
we're talking about here. I've written it.

I'm sorry to be so frankly but the two examples you provided shows
everything else but not a "dilemma" I "force upon people by bundling
expat with [my] code". This is plain wrong and nonsens.
